#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/oneplus/caihong

PRODUCT_COPY_FILES += \
    vendor/oneplus/caihong/proprietary/odm/etc/acdbdata/Audio_Parameter_Version.txt:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Audio_Parameter_Version.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/acdbdata/FTM/acdb_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/FTM/acdb_cal.acdb \
    vendor/oneplus/caihong/proprietary/odm/etc/acdbdata/FTM/workspaceFileXml.qwsp:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/FTM/workspaceFileXml.qwsp \
    vendor/oneplus/caihong/proprietary/odm/etc/acdbdata/MOS/acdb_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/MOS/acdb_cal.acdb \
    vendor/oneplus/caihong/proprietary/odm/etc/acdbdata/MOS/workspaceFileXml.qwsp:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/MOS/workspaceFileXml.qwsp \
    vendor/oneplus/caihong/proprietary/odm/etc/acdbdata/acdb_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/acdb_cal.acdb \
    vendor/oneplus/caihong/proprietary/odm/etc/camera/CameraHWConfiguration.config:$(TARGET_COPY_OUT_ODM)/etc/camera/CameraHWConfiguration.config \
    vendor/oneplus/caihong/proprietary/odm/etc/camera/CameraOemConfiguration.config:$(TARGET_COPY_OUT_ODM)/etc/camera/CameraOemConfiguration.config \
    vendor/oneplus/caihong/proprietary/odm/etc/camera/anc_cl_kernel.cache:$(TARGET_COPY_OUT_ODM)/etc/camera/anc_cl_kernel.cache \
    vendor/oneplus/caihong/proprietary/odm/etc/camera/fb_default:$(TARGET_COPY_OUT_ODM)/etc/camera/fb_default \
    vendor/oneplus/caihong/proprietary/odm/etc/camera/fwk_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/fwk_config.json \
    vendor/oneplus/caihong/proprietary/odm/etc/displaycolorfeaturecfg.xml:$(TARGET_COPY_OUT_ODM)/etc/displaycolorfeaturecfg.xml \
    vendor/oneplus/caihong/proprietary/odm/etc/dolby/display/dolby_vision.cfg:$(TARGET_COPY_OUT_ODM)/etc/dolby/display/dolby_vision.cfg \
    vendor/oneplus/caihong/proprietary/odm/etc/dolby/dolby_vision.cfg:$(TARGET_COPY_OUT_ODM)/etc/dolby/dolby_vision.cfg \
    vendor/oneplus/caihong/proprietary/odm/etc/init/hw/init.oplus.display.rc:$(TARGET_COPY_OUT_ODM)/etc/init/hw/init.oplus.display.rc \
    vendor/oneplus/caihong/proprietary/odm/etc/init/init.audio.rc:$(TARGET_COPY_OUT_ODM)/etc/init/init.audio.rc \
    vendor/oneplus/caihong/proprietary/odm/etc/init/init.nvram.rc:$(TARGET_COPY_OUT_ODM)/etc/init/init.nvram.rc \
    vendor/oneplus/caihong/proprietary/odm/etc/init/vendor.oplus.hardware.cammidasservice-V1-service.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vendor.oplus.hardware.cammidasservice-V1-service.rc \
    vendor/oneplus/caihong/proprietary/odm/etc/init/vendor.oplus.hardware.displaypanelfeature-service.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vendor.oplus.hardware.displaypanelfeature-service.rc \
    vendor/oneplus/caihong/proprietary/odm/etc/init/vendor.oplus.hardware.pogo_keyboard-service.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vendor.oplus.hardware.pogo_keyboard-service.rc \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Calibration360_2mic.dat:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Calibration360_2mic.dat \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Configuration.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Configuration.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID10_MIC_VR.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID10_MIC_VR.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID11_HE.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID11_HE.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID12_HE_APP1.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID12_HE_APP1.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID13_HE_APP2.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID13_HE_APP2.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID14_HE_Cam.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID14_HE_Cam.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID15_HE_Conference.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID15_HE_Conference.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID16_HE_Fast.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID16_HE_Fast.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID17_HE_Interview.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID17_HE_Interview.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID18_HE_Unprocess.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID18_HE_Unprocess.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID19_HE_Voice.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID19_HE_Voice.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID1_MIC_Normal.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID1_MIC_Normal.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID20_HE_VR.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID20_HE_VR.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID21_USB_Normal.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID21_USB_Normal.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID22_USB_APP1.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID22_USB_APP1.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID23_BT_Normal.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID23_BT_Normal.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID24_BT_APP1.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID24_BT_APP1.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID25_2mic_zoom.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID25_2mic_zoom.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID2_MIC_APP1.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID2_MIC_APP1.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID3_MIC_APP2.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID3_MIC_APP2.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID4_MIC_Cam.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID4_MIC_Cam.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID5_MIC_Conference.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID5_MIC_Conference.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID6_MIC_Fast.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID6_MIC_Fast.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID7_MIC_Interview.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID7_MIC_Interview.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID8_MIC_Unprocess.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID8_MIC_Unprocess.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/LVACFS_Parameter_ID9_MIC_Voice.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/LVACFS_Parameter_ID9_MIC_Voice.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_1.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_1.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_10.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_10.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_11.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_11.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_12.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_12.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_13.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_13.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_14.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_14.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_15.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_15.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_16.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_16.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_17.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_17.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_18.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_18.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_19.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_19.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_2.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_2.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_20.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_20.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_21.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_21.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_22.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_22.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_23.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_23.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_24.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_24.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_25.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_25.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_3.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_3.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_4.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_4.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_5.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_5.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_6.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_6.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_7.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_7.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_8.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_8.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/lvacfs_params/2mic/audiozoom_9.txt:$(TARGET_COPY_OUT_ODM)/etc/lvacfs_params/2mic/audiozoom_9.txt \
    vendor/oneplus/caihong/proprietary/odm/etc/media_codecs_dolby_vision.xml:$(TARGET_COPY_OUT_ODM)/etc/media_codecs_dolby_vision.xml \
    vendor/oneplus/caihong/proprietary/odm/etc/mixer_paths.xml:$(TARGET_COPY_OUT_ODM)/etc/mixer_paths.xml \
    vendor/oneplus/caihong/proprietary/odm/etc/resourcemanager.xml:$(TARGET_COPY_OUT_ODM)/etc/resourcemanager.xml \
    vendor/oneplus/caihong/proprietary/odm/etc/sensor/config/json_list:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/json_list \
    vendor/oneplus/caihong/proprietary/odm/etc/sensor/config/lanai_bu52053nvx_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_bu52053nvx_0.json \
    vendor/oneplus/caihong/proprietary/odm/etc/sensor/config/lanai_mtp_alsps.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_alsps.json \
    vendor/oneplus/caihong/proprietary/odm/etc/sensor/config/lanai_mtp_alsps_hw_tcs3701.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_alsps_hw_tcs3701.json \
    vendor/oneplus/caihong/proprietary/odm/etc/sensor/config/lanai_mtp_freefall.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_freefall.json \
    vendor/oneplus/caihong/proprietary/odm/etc/sensor/config/lanai_mtp_icm4x607.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_icm4x607.json \
    vendor/oneplus/caihong/proprietary/odm/etc/sensor/config/lanai_mtp_mmc56x3x.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_mmc56x3x.json \
    vendor/oneplus/caihong/proprietary/odm/etc/sensor/config/lanai_mtp_oplus_flight_detect.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/lanai_mtp_oplus_flight_detect.json \
    vendor/oneplus/caihong/proprietary/odm/etc/sensor/sensor_config.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/sensor_config.json \
    vendor/oneplus/caihong/proprietary/odm/etc/usecaseKvManager.xml:$(TARGET_COPY_OUT_ODM)/etc/usecaseKvManager.xml \
    vendor/oneplus/caihong/proprietary/odm/etc/wifi/kiwi/bdwlan.b0a:$(TARGET_COPY_OUT_ODM)/etc/wifi/kiwi/bdwlan.b0a \
    vendor/oneplus/caihong/proprietary/odm/etc/wifi/kiwi/bdwlan.b0c:$(TARGET_COPY_OUT_ODM)/etc/wifi/kiwi/bdwlan.b0c \
    vendor/oneplus/caihong/proprietary/odm/etc/wifi/kiwi/bdwlan.b0e:$(TARGET_COPY_OUT_ODM)/etc/wifi/kiwi/bdwlan.b0e \
    vendor/oneplus/caihong/proprietary/odm/etc/wifi/kiwi/bdwlan.elf:$(TARGET_COPY_OUT_ODM)/etc/wifi/kiwi/bdwlan.elf \
    vendor/oneplus/caihong/proprietary/odm/etc/wifi/kiwi/regdb.bin:$(TARGET_COPY_OUT_ODM)/etc/wifi/kiwi/regdb.bin \
    vendor/oneplus/caihong/proprietary/odm/firmware/aw882xx_acf.bin:$(TARGET_COPY_OUT_ODM)/firmware/aw882xx_acf.bin \
    vendor/oneplus/caihong/proprietary/odm/firmware/fastchg/charging_thermal_config_default.txt:$(TARGET_COPY_OUT_ODM)/firmware/fastchg/charging_thermal_config_default.txt \
    vendor/oneplus/caihong/proprietary/odm/firmware/tp/23926/FW_NT36532_HUAXING.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23926/FW_NT36532_HUAXING.img \
    vendor/oneplus/caihong/proprietary/odm/firmware/tp/23926/FW_NT36532_HUAXING_FAE.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23926/FW_NT36532_HUAXING_FAE.img \
    vendor/oneplus/caihong/proprietary/odm/firmware/tp/23926/FW_NT36532_HUAXING_TEST.bin:$(TARGET_COPY_OUT_ODM)/firmware/tp/23926/FW_NT36532_HUAXING_TEST.bin \
    vendor/oneplus/caihong/proprietary/odm/firmware/tp/23926/LIMIT_NT36532_HUAXING.img:$(TARGET_COPY_OUT_ODM)/firmware/tp/23926/LIMIT_NT36532_HUAXING.img \
    vendor/oneplus/caihong/proprietary/odm/firmware/ufs/SKhynix-HN8T05DEHKX073.bin:$(TARGET_COPY_OUT_ODM)/firmware/ufs/SKhynix-HN8T05DEHKX073.bin \
    vendor/oneplus/caihong/proprietary/odm/firmware/ufs/SKhynix-HN8T174EJKX075.bin:$(TARGET_COPY_OUT_ODM)/firmware/ufs/SKhynix-HN8T174EJKX075.bin \
    vendor/oneplus/caihong/proprietary/odm/firmware/ufs/SKhynix-HN8T274EJKX130.bin:$(TARGET_COPY_OUT_ODM)/firmware/ufs/SKhynix-HN8T274EJKX130.bin \
    vendor/oneplus/caihong/proprietary/odm/firmware/ufs/move_target_ufs_fw_to_oplusreserve1.sh:$(TARGET_COPY_OUT_ODM)/firmware/ufs/move_target_ufs_fw_to_oplusreserve1.sh \
    vendor/oneplus/caihong/proprietary/odm/firmware/ufs/ufs_version_config.xml:$(TARGET_COPY_OUT_ODM)/firmware/ufs/ufs_version_config.xml \
    vendor/oneplus/caihong/proprietary/odm/firmware/wireless_pen/23976/cps8601_firmware.bin:$(TARGET_COPY_OUT_ODM)/firmware/wireless_pen/23976/cps8601_firmware.bin \
    vendor/oneplus/caihong/proprietary/odm/firmware/wireless_pen/23978/cps8601_firmware.bin:$(TARGET_COPY_OUT_ODM)/firmware/wireless_pen/23978/cps8601_firmware.bin \
    vendor/oneplus/caihong/proprietary/odm/lib64/camera/awb_parameter_default.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/awb_parameter_default.bin \
    vendor/oneplus/caihong/proprietary/odm/lib64/camera/awb_parameter_lce_sc1320cs.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/awb_parameter_lce_sc1320cs.bin \
    vendor/oneplus/caihong/proprietary/odm/lib64/camera/awb_parameter_lce_sc820cs.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/awb_parameter_lce_sc820cs.bin \
    vendor/oneplus/caihong/proprietary/odm/lib64/camera/com.qti.sensormodule.lce_sc1320cs.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.lce_sc1320cs.bin \
    vendor/oneplus/caihong/proprietary/odm/lib64/camera/com.qti.sensormodule.lce_sc820cs.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.lce_sc820cs.bin \
    vendor/oneplus/caihong/proprietary/odm/lib64/camera/com.qti.tuned.lce_sc1320cs.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.lce_sc1320cs.bin \
    vendor/oneplus/caihong/proprietary/odm/lib64/camera/com.qti.tuned.lce_sc820cs.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.lce_sc820cs.bin \
    vendor/oneplus/caihong/proprietary/odm/lib64/camera/libaecCustomParam_Cam0.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/libaecCustomParam_Cam0.bin \
    vendor/oneplus/caihong/proprietary/odm/lib64/camera/libaecCustomParam_Cam1.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/libaecCustomParam_Cam1.bin \
    vendor/oneplus/caihong/proprietary/odm/lib64/camera/libafCustomParam_Cam0.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/libafCustomParam_Cam0.bin \
    vendor/oneplus/caihong/proprietary/odm/lib64/camera/libpdCustomParam_Cam0.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/libpdCustomParam_Cam0.bin \
    vendor/oneplus/caihong/proprietary/odm/lib64/camera/libpdCustomParam_Cam2.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/libpdCustomParam_Cam2.bin \
    vendor/oneplus/caihong/proprietary/odm/lib64/camera/libpdCustomParam_Cam3.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/libpdCustomParam_Cam3.bin \
    vendor/oneplus/caihong/proprietary/odm/lib64/camera/revision.txt:$(TARGET_COPY_OUT_ODM)/lib64/camera/revision.txt \
    vendor/oneplus/caihong/proprietary/odm/usr/idc/pogo_touchpad.idc:$(TARGET_COPY_OUT_ODM)/usr/idc/pogo_touchpad.idc \
    vendor/oneplus/caihong/proprietary/odm/vendor/etc/wifi/WCNSS_qcom_cfg.ini:$(TARGET_COPY_OUT_ODM)/vendor/etc/wifi/WCNSS_qcom_cfg.ini \
    vendor/oneplus/caihong/proprietary/odm/vendor/firmware/antdtx.b00:$(TARGET_COPY_OUT_ODM)/vendor/firmware/antdtx.b00 \
    vendor/oneplus/caihong/proprietary/odm/vendor/firmware/antdtx.b01:$(TARGET_COPY_OUT_ODM)/vendor/firmware/antdtx.b01 \
    vendor/oneplus/caihong/proprietary/odm/vendor/firmware/antdtx.b02:$(TARGET_COPY_OUT_ODM)/vendor/firmware/antdtx.b02 \
    vendor/oneplus/caihong/proprietary/odm/vendor/firmware/antdtx.b03:$(TARGET_COPY_OUT_ODM)/vendor/firmware/antdtx.b03 \
    vendor/oneplus/caihong/proprietary/odm/vendor/firmware/antdtx.b04:$(TARGET_COPY_OUT_ODM)/vendor/firmware/antdtx.b04 \
    vendor/oneplus/caihong/proprietary/odm/vendor/firmware/antdtx.b05:$(TARGET_COPY_OUT_ODM)/vendor/firmware/antdtx.b05 \
    vendor/oneplus/caihong/proprietary/odm/vendor/firmware/antdtx.b06:$(TARGET_COPY_OUT_ODM)/vendor/firmware/antdtx.b06 \
    vendor/oneplus/caihong/proprietary/odm/vendor/firmware/antdtx.b07:$(TARGET_COPY_OUT_ODM)/vendor/firmware/antdtx.b07 \
    vendor/oneplus/caihong/proprietary/odm/vendor/firmware/antdtx.b08:$(TARGET_COPY_OUT_ODM)/vendor/firmware/antdtx.b08 \
    vendor/oneplus/caihong/proprietary/odm/vendor/firmware/antdtx.mdt:$(TARGET_COPY_OUT_ODM)/vendor/firmware/antdtx.mdt \
    vendor/oneplus/caihong/proprietary/vendor/etc/2024-01-12_platform_RSA_license_a226ad89-a187-4b14-9447-d20bfe9dac1a.pfm:$(TARGET_COPY_OUT_VENDOR)/etc/2024-01-12_platform_RSA_license_a226ad89-a187-4b14-9447-d20bfe9dac1a.pfm \
    vendor/oneplus/caihong/proprietary/vendor/etc/clstc_config_library.xml:$(TARGET_COPY_OUT_VENDOR)/etc/clstc_config_library.xml \
    vendor/oneplus/caihong/proprietary/vendor/etc/display/DPU1010.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU1010.xml \
    vendor/oneplus/caihong/proprietary/vendor/etc/display/DPU10__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU10__.xml \
    vendor/oneplus/caihong/proprietary/vendor/etc/display/DPU870.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU870.xml \
    vendor/oneplus/caihong/proprietary/vendor/etc/display/DPU9__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU9__.xml \
    vendor/oneplus/caihong/proprietary/vendor/etc/display/advanced_sf_offsets.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/advanced_sf_offsets.xml \
    vendor/oneplus/caihong/proprietary/vendor/etc/display/qdcm_calib_data_Dual_dsi_csot_nt36532_video_mode_panel_with_DSC.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_Dual_dsi_csot_nt36532_video_mode_panel_with_DSC.json \
    vendor/oneplus/caihong/proprietary/vendor/etc/display/thermallevel_to_fps.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/thermallevel_to_fps.xml \
    vendor/oneplus/caihong/proprietary/vendor/etc/dolby_vision.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/dolby_vision.cfg \
    vendor/oneplus/caihong/proprietary/vendor/etc/init/feature_enabler_client.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/feature_enabler_client.rc \
    vendor/oneplus/caihong/proprietary/vendor/etc/init/init.qti.graphics.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.graphics.rc \
    vendor/oneplus/caihong/proprietary/vendor/etc/init/qdcmss.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qdcmss.rc \
    vendor/oneplus/caihong/proprietary/vendor/etc/init/vendor.qti.camera.provider-service_64.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.camera.provider-service_64.rc \
    vendor/oneplus/caihong/proprietary/vendor/etc/init/vendor.qti.hardware.display.color-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.display.color-service.rc \
    vendor/oneplus/caihong/proprietary/vendor/etc/oem_51_prj_OppoLTM8650_1689712162019.pfm:$(TARGET_COPY_OUT_VENDOR)/etc/oem_51_prj_OppoLTM8650_1689712162019.pfm \
    vendor/oneplus/caihong/proprietary/vendor/etc/snapdragon_color_libs_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/snapdragon_color_libs_config.xml \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b00 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b01 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b02 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b03 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b04 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b05 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b06 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b07 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b08 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b09 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b10 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b11 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b12 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b13 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b14 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b15 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b16 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b17 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b18 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b19 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b20 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.mbn \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.mdt \
    vendor/oneplus/caihong/proprietary/vendor/firmware/CAMERA_ICP_170.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP_170.elf \
    vendor/oneplus/caihong/proprietary/vendor/firmware/dpAP_full.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/dpAP_full.mbn \
    vendor/oneplus/caihong/proprietary/vendor/firmware/dpAP_mini.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/dpAP_mini.mbn \
    vendor/oneplus/caihong/proprietary/vendor/firmware/dpAP_modemssr.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/dpAP_modemssr.mbn \
    vendor/oneplus/caihong/proprietary/vendor/firmware/dpMSA.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/dpMSA.mbn \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass-lt.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b00 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass-lt.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b01 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass-lt.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b02 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass-lt.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b03 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass-lt.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b04 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass-lt.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b05 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass-lt.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b06 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass-lt.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b07 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass-lt.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b08 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass-lt.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b09 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass-lt.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b10 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass-lt.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b11 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass-lt.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b12 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass-lt.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b13 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass-lt.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b14 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass-lt.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b15 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass-lt.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b16 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass-lt.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b17 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass-lt.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b18 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass-lt.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b19 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass-lt.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.mbn \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass-lt.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.mdt \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b00 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b01 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b02 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b03 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b04 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b05 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b06 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b07 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b08 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b09 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b10 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b11 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b12 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b13 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b14 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b15 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b16 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b17 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b18 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b19 \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.mbn \
    vendor/oneplus/caihong/proprietary/vendor/firmware/evass.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.mdt \
    vendor/oneplus/caihong/proprietary/vendor/firmware/gen70900_aqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70900_aqe.fw \
    vendor/oneplus/caihong/proprietary/vendor/firmware/gen70900_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70900_sqe.fw \
    vendor/oneplus/caihong/proprietary/vendor/firmware/gen70900_zap.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70900_zap.mbn \
    vendor/oneplus/caihong/proprietary/vendor/firmware/gen71100_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gen71100_gmu.bin \
    vendor/oneplus/caihong/proprietary/vendor/firmware/gen71100_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen71100_sqe.fw \
    vendor/oneplus/caihong/proprietary/vendor/firmware/gen71100_zap.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/gen71100_zap.mbn \
    vendor/oneplus/caihong/proprietary/vendor/firmware/gmu_gen70900.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gmu_gen70900.bin \
    vendor/oneplus/caihong/proprietary/vendor/firmware/qps615_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/qps615_fw.bin \
    vendor/oneplus/caihong/proprietary/vendor/firmware/tof8801_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tof8801_firmware.bin \
    vendor/oneplus/caihong/proprietary/vendor/firmware/vpu20_2v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.mbn \
    vendor/oneplus/caihong/proprietary/vendor/firmware/vpu20_2v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v_unsigned.mbn \
    vendor/oneplus/caihong/proprietary/vendor/firmware/vpu20_4v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.mbn \
    vendor/oneplus/caihong/proprietary/vendor/firmware/vpu20_4v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v_unsigned.mbn \
    vendor/oneplus/caihong/proprietary/vendor/firmware/vpu30_2v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu30_2v.mbn \
    vendor/oneplus/caihong/proprietary/vendor/firmware/vpu30_2v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu30_2v_unsigned.mbn \
    vendor/oneplus/caihong/proprietary/vendor/firmware/vpu33_4v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu33_4v.mbn \
    vendor/oneplus/caihong/proprietary/vendor/firmware/vpu33_4v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu33_4v_unsigned.mbn \
    vendor/oneplus/caihong/proprietary/vendor/gpu/kbc/sequence_manifest.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/sequence_manifest.bin \
    vendor/oneplus/caihong/proprietary/vendor/gpu/kbc/unified_kbcs_64.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/unified_kbcs_64.bin \
    vendor/oneplus/caihong/proprietary/vendor/gpu/kbc/unified_ksqs.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/unified_ksqs.bin \
    vendor/oneplus/caihong/proprietary/vendor/lib64/camera/bitmlconfig.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/bitmlconfig.bin \
    vendor/oneplus/caihong/proprietary/vendor/lib64/camera/bitmlconfig_sm8635.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/bitmlconfig_sm8635.bin \
    vendor/oneplus/caihong/proprietary/vendor/lib64/camera/camxfl115indices.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/camxfl115indices.bin \
    vendor/oneplus/caihong/proprietary/vendor/lib64/camera/camxfl300v1indices.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/camxfl300v1indices.bin \
    vendor/oneplus/caihong/proprietary/vendor/lib64/camera/camxfl300v2indices.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/camxfl300v2indices.bin \
    vendor/oneplus/caihong/proprietary/vendor/lib64/camera/camxflcustom300indices.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/camxflcustom300indices.bin \
    vendor/oneplus/caihong/proprietary/vendor/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.bin \
    vendor/oneplus/caihong/proprietary/vendor/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/oneplus/caihong/proprietary/vendor/lib64/camera/fdconfigsecure.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigsecure.bin \
    vendor/oneplus/caihong/proprietary/vendor/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.bin \
    vendor/oneplus/caihong/proprietary/vendor/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideolite.bin \
    vendor/oneplus/caihong/proprietary/vendor/lib64/libpnc_cl_program.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/libpnc_cl_program.bin

PRODUCT_PACKAGES += \
    com.arcsoft.node.smooth_transition \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.hwcfg.bps \
    com.qti.hwcfg.ife \
    com.qti.hwcfg.ipe \
    com.qti.hwcfg.tfe \
    com.qti.node.afbfusion \
    com.qti.node.aon \
    com.qti.node.customhwnode \
    com.qti.node.depth \
    com.qti.node.depthprovider \
    com.qti.node.dewarp \
    com.qti.node.dummydepth \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.evadepth \
    com.qti.node.evs \
    com.qti.node.fcv \
    com.qti.node.formatconversion \
    com.qti.node.gme \
    com.qti.node.gpu \
    com.qti.node.gyrornn \
    com.qti.node.hdr10pgen \
    com.qti.node.hdr10phist \
    com.qti.node.itofpreprocess \
    com.qti.node.memcpy \
    com.qti.node.ml \
    com.qti.node.mlinference \
    com.qti.node.muxer \
    com.qti.node.remosaic \
    com.qti.node.seg \
    com.qti.node.stich \
    com.qti.node.swaidenoiser \
    com.qti.node.swbestats \
    com.qti.node.swcac \
    com.qti.node.swec \
    com.qti.node.swfusion \
    com.qti.node.swhme \
    com.qti.node.swlsc \
    com.qti.node.swmctf \
    com.qti.node.swpdpc \
    com.qti.node.swpnc \
    com.qti.node.swpreprocess \
    com.qti.node.swregistration \
    com.qti.node.swvrt \
    com.qti.stats.aec \
    com.qti.stats.aecwrapper \
    com.qti.stats.aecxcore \
    com.qti.stats.af \
    com.qti.stats.afc \
    com.qti.stats.afd \
    com.qti.stats.afwrapper \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbr \
    com.qti.stats.awbwrapper \
    com.qti.stats.cnndriver \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.localhistogram \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.roimixer \
    com.qti.stats.roimixerlib \
    com.qti.stats.statsgenerator \
    com.qti.stats.tracker \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    libcamxevainterface \
    libdepthmapwrapper \
    libdepthmapwrapper_itof \
    libdepthmapwrapper_secure \
    camx.device-impl \
    camx.provider-impl \
    com.qti.camx.chiiqutils \
    com.qti.chiusecaseselector \
    com.qti.feature2.afbrckt \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.derivedoffline \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs.sm8650 \
    com.qti.feature2.hdr \
    com.qti.feature2.mcreprocrt \
    com.qti.feature2.memcpy \
    com.qti.feature2.metadataserializer \
    com.qti.feature2.mfsr \
    com.qti.feature2.ml \
    com.qti.feature2.mux \
    com.qti.feature2.qcfa \
    com.qti.feature2.rawhdr \
    com.qti.feature2.realtimeserializer \
    com.qti.feature2.rt \
    com.qti.feature2.rtmcx \
    com.qti.feature2.serializer \
    com.qti.feature2.statsregeneration \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    com.qti.qseeaon \
    com.qti.qseeutils \
    com.qti.settings.sm8650 \
    com.qti.stats.common \
    com.qualcomm.mcx.distortionmapper \
    com.qualcomm.mcx.linearmapper \
    com.qualcomm.mcx.nonlinearmapper \
    com.qualcomm.mcx.policy.mfl \
    com.qualcomm.qti.mcx.usecase.extension \
    camera.qcom.sm8650 \
    camera.qcom \
    com.qti.chi.offline \
    com.qti.chi.override \
    libGCore4Cell_32E2 \
    libPanelChaplin \
    libRGBC \
    libSonyIMX471RmscLibrary \
    libaidenoiser \
    libaidenoiserv2 \
    libarcsoft_triple_sat \
    libarcsoft_triple_zoomtranslator \
    libbacklight-calib \
    libbitmlengine \
    libbitmlenginev2 \
    libcamerapostproc \
    libcamxcommonutils \
    libcamxexternalformatutils \
    libcamxfdengine \
    libcamxhwnodecontext \
    libcamxifestriping \
    libcamximageformatutils \
    libcamxjson \
    libcamxncsdatafactory \
    libcamxqsatalgo \
    libcamxsettingsmanager \
    libcamxstatscore \
    libcamxswispiqmodule \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libchifeature2 \
    libchilog \
    libclstc_algorithm_adapter \
    libclstc_gcp_adapter \
    libclstc_tm \
    libcom.qti.chinodeutils \
    libcommonchiutils \
    libcwb_client_vendor \
    libcwb_qcom_aidl \
    libdepthcomputation \
    libdigital-dimming \
    libdisp-aba \
    libdisplayconfig.qti \
    libdisplayqos \
    libdisplayskuutils \
    libdpp_manager \
    libdpps \
    libdualcam_optical_zoom_control_vendor \
    libdualcam_video_optical_zoom_vendor \
    libeepromcutter \
    libfeutils \
    libgame_enhance \
    libhdr10plus \
    libhdr_backlight_adapter \
    libhdr_stub \
    libhdr_tm \
    libhdrdynamic \
    libhdrdynamicootf \
    libhdrvivid \
    libhistogram \
    libhme \
    libhwconfigurationutil_vendor \
    libintervmipc \
    libipebpsstriping \
    libipebpsstriping170 \
    libipebpsstriping480 \
    libisphwsetting \
    libjni_aidenoiserutilv2 \
    libjni_imageutil \
    libjpege \
    libmctfengine_stub \
    libmemutils \
    libmfGhostDetection \
    libmfec \
    libmidasserviceintf \
    libmidasserviceintf_aidl \
    libmmcamera_bestats \
    libmmcamera_cac \
    libmmcamera_lscv35 \
    libmmcamera_mfnr \
    libmmcamera_mfnr_t4 \
    libmmcamera_pdpc \
    libmmcamera_pnc \
    libopencv \
    libopencv3a \
    libopestriping \
    libpwirisfeature_vendor \
    libpwirishal \
    libpwirishalwrapper_vendor \
    libqdcm-algo \
    libqdcm-json-mode-parser \
    libqdcm-mode-parser \
    libqdutils \
    libqll \
    libqll10 \
    libqllengine \
    libqrtrclient \
    libqseed3 \
    libqsegnet \
    libqshcamera \
    librcmask \
    libsdedrm \
    libsdm-color \
    libsdm-colormgr-algo \
    libsdm-disp-vndapis \
    libsdmcore \
    libsdmdal \
    libsdmextension \
    libsdmutils \
    libsfeShiftExtrapolation \
    libsgutils2 \
    libsnapdragoncolor-manager \
    libsnapdragoncolor-qdcm \
    libspectre \
    libswregistrationalgo \
    libtestutils \
    libtfestriping \
    libtinyxml2_1 \
    libtriplecam_optical_zoom_control \
    libtriplecam_video_optical_zoom \
    libubifocus \
    libvideoml \
    libvmfilexfer \
    sensors.qsh \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.color@1.3 \
    vendor.display.color@1.4 \
    vendor.display.color@1.5 \
    vendor.display.postproc@1.0 \
    vendor.oplus.hardware.camera.aon-service-impl \
    vendor.oplus.hardware.cammidasservice@1.0 \
    vendor.pixelworks.hardware.display-V2-ndk \
    vendor.pixelworks.hardware.display@1.0_vendor \
    vendor.pixelworks.hardware.display@1.1_vendor \
    vendor.pixelworks.hardware.display@1.2_vendor \
    vendor.pixelworks.hardware.feature-V1-ndk \
    vendor.pixelworks.hardware.feature@1.0_vendor \
    vendor.pixelworks.hardware.feature@1.1_vendor \
    vendor.qti.hardware.camera.aon-service-impl \
    vendor.qti.hardware.camera.offlinecamera-service-impl \
    vendor.qti.hardware.camera.postproc@1.0-service-impl \
    vendor.qti.hardware.qdutils_disp@1.0 \
    libQnnHtp.aiboost \
    libQnnHtpPrepare.aiboost \
    libQnnHtpV75Stub.aiboost \
    libQnnSystem.aiboost \
    libQnnHtpV75Skel.signed.aiframe \
    libQnnHtpV75Skel.unsigned.aiframe \
    libQnnHtp.aiframe \
    libQnnHtpPrepare.aiframe \
    libQnnHtpV75Stub.aiframe \
    libQnnSystem.aiframe \
    libaiboost_qnn_external_delegate \
    libqcom_llm \
    libtransformer_lite \
    com.qti.sensor.sc1320cs \
    com.qti.sensor.sc820cs \
    com.oplus.node.mvgsat \
    com.oplus.node.preview \
    com.oplus.node.sstabdefer \
    com.oplus.node.sstabgme \
    com.oplus.node.sstabphoto \
    com.oplus.node.sstabrealt \
    camera.oemlayer \
    lib2DSlender \
    libAF \
    libAIEngine \
    libAlgoInterface \
    libAlgoProcess \
    libAncFilter \
    libAncHumVideoBase \
    libAncHumanDoubleExposure \
    libAncHumanSegFigureFusion \
    libAncSegBaseSdk \
    libAncSegMultiSdk \
    libAncSegmentSdk \
    libBasicTonePhoto \
    libBokehPre \
    libCOppLceTonemapAPI \
    libCS \
    libCaptureBokeh \
    libDeVIS \
    libEIS \
    libFDClite \
    libFaceBeautyCap \
    libFaceBeautyJni \
    libFaceBeautyPICap \
    libFaceBeautyPre \
    libFaceDistortionCorrection \
    libFilterWrapper \
    libHDRDetection \
    libHIS \
    libImageWarpMask \
    libODNN \
    libOGLManager \
    libOPAlgoCamAIBeautyBodyDetection \
    libOPAlgoCamAiBeautyEyeRetouchCn \
    libOPAlgoCamAiBeautyFaceRetouchCn \
    libOPAlgoCamAiUnifySkin \
    libOPAlgoCamFaceBeautyCap \
    libOPAlgoCamFaceRestore \
    libOPAlgoCamHybridRaw \
    libOPAlgoCamSinglePortrait \
    libOPLUSMotionDetection \
    libOplusPDCore \
    libOpo_awb \
    libPerfectColor \
    libPerfectlyClearCruxOpt \
    libPlatformValidatorShared \
    libPolarrRender \
    libPreviewDecisionOld \
    libQnnCpu \
    libQnnGpu \
    libQnnHtp \
    libQnnHtpPrepare \
    libQnnHtpV75CalculatorStub \
    libQnnHtpV75Stub \
    libQnnSaver \
    libQnnSystem \
    libRedeyeReduce \
    libSNPE \
    libSnpeHta \
    libSnpeHtpPrepare \
    libSnpeHtpV75Stub \
    libSuperRaw \
    libSuperTextWrapper \
    libUpScale \
    libVDBayerHDR \
    libVDBlurless \
    libVDExternal \
    libVDSuperPhotoAPI \
    libWaterMark \
    libXDocProcessSDK \
    libYTCommon \
    lib_geofencing \
    lib_lvacfs \
    lib_rectify \
    libaecCustom \
    libaecCustomParamParser \
    libafCustomParamParser \
    libaiboost \
    libaiboost_llm \
    libaiboost_qnn_external_delegate_te \
    libaiboost_qnn_sr \
    libaiboost_sr \
    libaiboost_te \
    libaiboost_ubwc \
    libaideblur \
    libaisal \
    libaisd \
    libaiseg \
    libaisr \
    libalCFR \
    libalog \
    libancbase_rt_fusion \
    libancbase_segbase \
    libancbase_segment \
    libancbase_segmulti \
    libapsexif \
    libapsjpeg \
    libapspng \
    libapsyuv \
    libarc.ion \
    libarcsoft_distortion_correction \
    libarcsoft_dualcam_bokeh_api \
    libarcsoft_dualcam_refocus_left \
    libarcsoft_dualcam_refocus_preview \
    libarcsoft_dualcam_refocus_uw \
    libarcsoft_hdr_denoise_api \
    libarcsoft_high_dynamic_range \
    libarcsoft_high_dynamic_range_couple_v4 \
    libarcsoft_high_dynamic_range_v4 \
    libarcsoft_lensstaindetection \
    libarcsoft_long_exposure_capture \
    libarcsoft_long_exposure_preview \
    libarcsoft_low_light_hdr \
    libarcsoft_merge_hdr_denoise_api \
    libarcsoft_preview_antibanding \
    libarcsoft_qnnhtp \
    libarcsoft_quad_sr_grf \
    libarcsoft_quad_super_resolution_raw \
    libarcsoft_quad_super_resolution_raw_func \
    libarcsoft_scbokeh_video \
    libarcsoft_smart_denoise \
    libarcsoft_smart_denoise_v4 \
    libarcsoft_turbo_fusion_raw_portrait_super_night \
    libarcsoft_turbo_fusion_raw_super_night \
    libarcsoft_turbo_hdr_grf \
    libarcsoft_turbo_hdr_raw \
    libarcsoft_turbo_hdr_raw_front \
    libarcsoft_turbo_raw \
    libarcsoft_ultra_high_dynamic_range \
    libarcsoft_videoautozoom \
    libc++_shared \
    libcalculator \
    libcalculator_htp \
    libcreatebin \
    libcvface_api \
    libdisplayaidlapis \
    libdisplaycolorfeature \
    libdisplayfossfeature_nature \
    libdolbyclstc \
    libdpaservice \
    libeffect_custom \
    libexif-jpeg-aps \
    libextendfile \
    libextensionlayer \
    libhta_hexagon_runtime_snpe \
    libhwconfigurationutil \
    libhybridraw \
    libhybridsr_datas \
    libhybridsr_tuningparams \
    libhyperlapse \
    libiceainr \
    libimgClarityEvaluate \
    liblvacfs_wrapper \
    libmpbase \
    libmsnativefilter \
    libmvgcommon \
    libnpu \
    libnvram \
    libocce3a \
    liboemconfigurationutil \
    liboplusblur_capture_api \
    libpdCustomParamParser \
    libpngwrapper \
    libpogo_keyboard \
    libportrait_repair_qnn \
    libpwirisfeature \
    libpwirishalwrapper \
    libqsh.utils \
    libremosaic_wrapper \
    libroi \
    libsaveshaderbin \
    libsharebuffer \
    libsharebuffer_impl \
    libsnpe_loader \
    libstblur_api \
    libstblur_capture_api \
    libstface_datas \
    libstface_fd_api \
    libstfd_mobile_api \
    libtensorflowlite_oplus \
    libtfa98xx \
    libthirdcapability \
    libtrace \
    libtriplecam_image_optical_zoom \
    libvega_common \
    libvega_face \
    libwatermark_photo \
    libwrapper_te \
    libyuv2 \
    libyuvwrapper \
    libzlib \
    libQnnHtp.oplusmss \
    libQnnHtpPrepare.oplusmss \
    libQnnHtpV75Stub.oplusmss \
    libQnnSystem.oplusmss \
    libaiboost.oplusmss \
    libaiboost_qnn_external_delegate.oplusmss \
    vendor.oplus.hardware.camera_rfi-V1-service-impl \
    vendor.oplus.hardware.sendextcamcmd-V1-service-impl \
    vendor.pixelworks.hardware.display@1.0 \
    vendor.pixelworks.hardware.display@1.1 \
    vendor.pixelworks.hardware.display@1.2 \
    vendor.pixelworks.hardware.feature@1.0 \
    vendor.pixelworks.hardware.feature@1.1 \
    odm_lib_rfsa_adsp_aiboost_signed_libQnnHtpV75Skel_so \
    odm_lib_rfsa_adsp_aiboost_signed_libaiboostubwc_skel_so \
    odm_lib_rfsa_adsp_capi_v3_oprec_so \
    odm_lib_rfsa_adsp_libCalculator_skel_so \
    odm_lib_rfsa_adsp_libQnnHtpV75_so \
    odm_lib_rfsa_adsp_libQnnHtpV75Skel_so \
    odm_lib_rfsa_adsp_libQnnSaver_so \
    odm_lib_rfsa_adsp_libSnpeHtpV75Skel_so \
    odm_lib_rfsa_adsp_libSuperRawPost_skel_so \
    odm_lib_rfsa_adsp_libaisr_skel_so \
    odm_lib_rfsa_adsp_libarc_htp_driver_skel_so \
    odm_lib_rfsa_adsp_libcalculator_skel_so \
    odm_lib_rfsa_adsp_libhvxFaceBeautyPre_skel_so \
    odm_lib_rfsa_adsp_libktveffect_so \
    odm_lib_rfsa_adsp_libvdblurless_5_0_2_skel_so \
    odm_lib_rfsa_adsp_libvdsuperphoto_skel_so \
    odm_lib_rfsa_adsp_oplusmss_unsigned_libQnnHtpV75Skel_so \
    vendor.qti.camera.aon-impl.xml \
    vendor.qti.camera.offlinecamera-impl.xml \
    vendor.qti.camera.postproc-impl.xml \
    vendor.qti.camera.provider.xml \
    manifest_displaycolorfeature_aidl.xml \
    manifest_oplus_camera_rfi.xml \
    manifest_oplus_cammidasservice_aidl.xml \
    manifest_oplus_cwb_aidl.xml \
    manifest_oplus_displaypanelfeature_aidl.xml \
    manifest_oplus_sendextcamcmd.xml \
    vendor.oplus.hardware.pogo_keyboard.xml \
    feature_enabler_client \
    vendor.qti.camera.provider-service_64 \
    vendor.qti.hardware.display.color-service \
    vendor.qti.hardware.display.composer-service \
    init.qti.graphics \
    ppd \
    qdcmss \
    cwb_utils_aidl \
    vendor.oplus.hardware.cammidasservice-V1-service \
    vendor.oplus.hardware.displaypanelfeature-service \
    vendor.oplus.hardware.pogo_keyboard-service \
    nvram_qmi \
    nvram_server

PRODUCT_PACKAGES += \
    odm_firmware_wireless_pen_23926_cps8601_firmware_bin \
    odm_firmware_wireless_pen_23927_cps8601_firmware_bin
